ALTER TABLE wine 
ADD sommelier VARCHAR(255) NULL;

ALTER TABLE wine 
ADD image VARCHAR(255) NOT NULL;

ALTER TABLE wine 
ADD website VARCHAR(255) NULL;

ALTER TABLE wine 
ADD specificities VARCHAR(255) NULL;

ALTER TABLE wine 
ADD producteur VARCHAR(255) NULL;